# Dockerfile

FROM ubuntu
MAINTAINER Christian Lundkvist <christian.lundkvist@gmail.com>

USER root

RUN apt-get -y update

RUN curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash - && sudo apt-get install -y nodejs

# build dependencies

RUN apt-get install -y --no-install-recommends git

RUN cd /opt/ && git clone https://github.com/uport-project/uport-did-driver.git

# done

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

EXPOSE 8080

CMD ["/usr/bin/node", "/opt/uport-did-driver/expressresolver.js"]

